### ISSUE TITLE
Not compatible with Java 22

### ISSUE THREAD

**Issue by kappa-maintainer** [toolfactory/jvm-driver#70]
```
Caused by: io.github.toolfactory.jvm.Driver$InitializeException: Could not initialize NativeDriver
	at io.github.toolfactory.jvm.DriverAbst.init(DriverAbst.java:177)
	at top.outlands.foundation.boot.JVMDriverHolder.<clinit>(JVMDriverHolder.java:15)
	... 12 more
Caused by: io.github.toolfactory.jvm.util.ObjectProvider$BuildingException: Exception occurred while retrieving the implementation of class io.github.toolfactory.jvm.function.catalog.ConstructorInvokeFunction (jvm architecture: x64, jvm version: 22, jvm vendor: Azul Systems, Inc.)
	at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObject(ObjectProvider.java:95)
	at io.github.toolfactory.jvm.DriverAbst.getOrBuildConstructorInvoker(DriverAbst.java:411)
	at io.github.toolfactory.jvm.DriverAbst.init(DriverAbst.java:136)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObjectInternal(ObjectProvider.java:144)
	at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObject(ObjectProvider.java:92)
	... 15 more
Caused by: java.lang.ClassNotFoundException: jdk.internal.reflect.NativeConstructorAccessorImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.base/java.lang.Class.forName(Unknown Source)
	at io.github.toolfactory.jvm.function.catalog.ConstructorInvokeFunction$ForJava9.<init>(ConstructorInvokeFunction.java:70)
	... 20 more
```

`NativeConstructorAccessorImpl` is gone in Java 22

**Comment by Roberto-Gentili** [comment]
Fixed with version [9.7.0](https://github.com/toolfactory/jvm-driver/actions/runs/8904394127)

**Comment by Roberto-Gentili** [comment]
Fixed with version [9.7.0](https://github.com/toolfactory/jvm-driver/actions/runs/8904394127)

**Comment by kappa-maintainer** [comment]
Thanks! Waiting on maven central

**Comment by Roberto-Gentili** [comment]
> Thanks! Waiting on maven central

It's already on Maven central

**Comment by kappa-maintainer** [comment]
Sorry, mvn web page syncing is slow
